services:
  - type: web
    name: wevibe-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false   # à renseigner dans le dashboard Render
      - key: ANTHROPIC_API_KEY
        sync: false   # à renseigner dans le dashboard Render
      - key: PYTHON_VERSION
        value: "3.11.0"
